name: Install and Test Scripts

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Run installation script
        run: |
          chmod +x ./install.sh
          ./install.sh

      # Test scripts for valid return codes
      - name: Run scripts and check for valid return codes
        run: |
          # Example of testing scripts in a folder or a specific script
          for script in ./scripts/*.sh; do
            chmod +x "$script"
            "$script"  # Run the script
            if [[ $? -ne 0 ]]; then
              echo "Script $script failed with return code $?" 
              exit 1
            fi
          done

      # Additional steps can be added here for reporting or other tasks
